### PR TITLE
Dark Mode added  

### PR DESCRIPTION
**Pull request by nightfury-crypto**
now you can use dark mode. 
**1 additional javascript file is added and 2 changes in existing files. added button in index.html and added some css to make it fany in stylesheet.**

**LIGHT MODE PREVIEW**
light mode

**DARK MODE**
dark mode

by karnail singh choudhary
instagram - @ig_toothless__ ( https://www.instagram.com/ig_toothless__/  )

### CODE REVIEW

**Comment by nightfury-crypto** [comment]
You didn't liked my dark mode setting for your website? You closed by pull
request. It was also regarding hackertoberfest. But it's ok at least reply
me 'no you don't want any dark mode for your website.' ☹️

**Comment by jonbarron** [comment]
Yes before you spend time writing code for an open-source codebase, you should talk to the people currently maintaining it to see if the thing you want to write is actually something that they would be willing to merge into the codebase. Otherwise just fork the repo.

**Comment by nightfury-crypto** [comment]
Ok thank you for replying me. 🙂.

**Comment by nightfury-crypto** [comment]
I had wrote that code for hacktoberfest. But i only want to do something
good in your project. I wrote it because i thought you would like it. But i
was wrong. ( I added dark mode because maximum website have it.) Everyone
like dark mode nowadays. But it's ok . Sorry for that. And thank you for
replying me.

**Pull request closed without merging**
